<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>catalyst</ToolCommandName>
        <PackageId>catalyst-cli</PackageId>
        <Version>0.1.0</Version>
        <Description>Modular CLI toolkit for automating code generation and development tasks</Description>
        <Authors>alexpetrou94</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/alexpetrou94/catalyst</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Catalyst.Tests" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Catalyst.Tests\**\*.cs" />
        <None Remove="Catalyst.Tests\**" />
        <None Include=".examples\generated-api-example.ts" />
        <None Include=".examples\openapi-example.json" />
        <None Include=".examples\openapi-invalid.json" />
        <None Include=".examples\out.ts" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.OpenApi" Version="3.9.0" />
      <PackageReference Include="Spectre.Console" Version="0.55.2" />
      <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
      <PackageReference Include="UPhoricLibrary" Version="0.2026.223.13" />
    </ItemGroup>

</Project>
